# Generated by Django 5.1.2 on 2024-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_releaseyear', models.PositiveIntegerField()),
                ('movie_category', models.CharField(max_length=100)),
                ('movie_duration', models.PositiveIntegerField()),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('movie_review', models.DecimalField(decimal_places=2, max_digits=3)),
                ('movie_poster', models.URLField(default='https://png.pngtree.com/element_our/png/20181227/movie-icon-which-is-designed-for-all-application-purpose-new-png_287896.jpg')),
                ('movie_description', models.TextField()),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_writers', models.CharField(max_length=100)),
                ('movie_stars', models.CharField(max_length=100)),
            ],
        ),
    ]
