# Generated by Django 5.1.2 on 2024-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_boxoffice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_budget',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_certificate',
            field=models.CharField(default='Nil', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_tagline',
            field=models.CharField(default='Nil', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.URLField(default='https://png.pngtree.com/element_our/png/20181227/movie-icon-which-is-designed-for-all-application-purpose-new-png_287896.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_stars',
            field=models.CharField(max_length=10000),
        ),
    ]
