# Generated by Django 5.1.2 on 2024-10-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0002_movie_movie_boxoffice_movie_movie_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_review',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
